schema = 3

[mod]
  [mod.'github.com/alecthomas/chroma']
    version = 'v0.10.0'
    hash = 'sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ='

  [mod.'github.com/danieljoos/wincred']
    version = 'v1.2.3'
    hash = 'sha256-lDRkd1rU5EIyhzzCB0yIuQUpSdvMM2jjUsCg7rQaHMQ='

  [mod.'github.com/diamondburned/adaptive']
    version = 'v0.0.2-0.20221227093656-fa139be203a8'
    hash = 'sha256-xIerrbYQf6FPbbRd60OnBStIJMl6mg/Qvl+LTmRbyIw='

  [mod.'github.com/diamondburned/arikawa/v3']
    version = 'v3.6.0'
    hash = 'sha256-FxQG+xXZ8EIpV1IYCwoN20BK+V+b1uiZWPcP98lhBuw='

  [mod.'github.com/diamondburned/chatkit']
    version = 'v0.0.0-20240614105536-5788b19145bc'
    hash = 'sha256-w6q9vDTUmSwAn6RDhPUzY2VIAvgduSbSxGzh46gLFqQ='

  [mod.'github.com/diamondburned/gotk4-adwaita/pkg']
    version = 'v0.0.0-20260808200908-d4aecaa0ff32'
    hash = 'sha256-GbOZg9FPkwsGl0lA4kbNax7vBtBJc8lllLAOPBv74Wg='

  [mod.'github.com/diamondburned/gotk4/pkg']
    version = 'v0.4.1'
    hash = 'sha256-ByHw9QuTw3gYsalDt+HUCLYZjL6sEX+aE63lOlwX8wc='

  [mod.'github.com/diamondburned/gotkit']
    version = 'v0.0.0-20260808214113-d0c316dcdb4e'
    hash = 'sha256-6/Ow9vCb0pJlL62c5BKmdzL4Eb4pelopCn4uZ7jX/Tg='

  [mod.'github.com/diamondburned/ningen/v3']
    version = 'v3.0.1-0.20250703054403-e5dc4cf15e84'
    hash = 'sha256-bpl5Ynwfish8jO55PJu4Exu7mAnXUBYu4aJ+wy5ZReU='

  [mod.'github.com/dlclark/regexp2']
    version = 'v1.12.0'
    hash = 'sha256-PVX2rDCkiG0vyA1CbDi3bzLeZ2T8hcqJv3pZ5YwGzMI='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/enescakir/emoji']
    version = 'v1.0.0'
    hash = 'sha256-fnYYIR2EQG7CfdEdY8Mui2wVTmrcd0KhZD+SZLXT0fY='

  [mod.'github.com/godbus/dbus/v5']
    version = 'v5.2.2'
    hash = 'sha256-j+LicPlXcB1R3oVFPa8cd4yVJLpBx+ca5gXmHqOJSN8='

  [mod.'github.com/gorilla/schema']
    version = 'v1.4.1'
    hash = 'sha256-1sWmntFnTzzy95TtHSJJEUJpEruVBy7eA38vX8kJ85k='

  [mod.'github.com/gorilla/websocket']
    version = 'v1.5.3'
    hash = 'sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0='

  [mod.'github.com/ianlancetaylor/cgosymbolizer']
    version = 'v0.0.0-20260706211533-3db786f0ca59'
    hash = 'sha256-tznv0R5dMxSDVUdgKHrycIZOKEMrGJm2JInVYg2C9/M='

  [mod.'github.com/leonelquinteros/gotext']
    version = 'v1.7.2'
    hash = 'sha256-qWopQ/gt8frbHEGhCql1ozpWF1KX9yqWCbIXkOmPESU='

  [mod.'github.com/lmittmann/tint']
    version = 'v1.2.0'
    hash = 'sha256-6smewubE3uhGg4mD/GSar7J1/dfeZ4w2wQIXIixzlyw='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.24'
    hash = 'sha256-pmq8KKIb2+qMF3E1cR2B7NAj5joF2tZduyXjIfIlkTk='

  [mod.'github.com/pkg/errors']
    version = 'v0.9.1'
    hash = 'sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw='

  [mod.'github.com/puzpuzpuz/xsync/v3']
    version = 'v3.5.1'
    hash = 'sha256-yAf9Ye4XmtnhK3cxaUCjdGZWH+0WRNIczwCW3CPKUUw='

  [mod.'github.com/sahilm/fuzzy']
    version = 'v0.1.3'
    hash = 'sha256-iIUiVfjmgB927jbdLrtrQrrXKcOfhvMHnC+65UZAyNY='

  [mod.'github.com/twmb/murmur3']
    version = 'v1.1.8'
    hash = 'sha256-j5uSr5TfAFeiCWcG3I6WmVrwEuAe57FSHbEQ9tZbixg='

  [mod.'github.com/yalue/merged_fs']
    version = 'v1.3.0'
    hash = 'sha256-Ww4EEsieMo7UzQYRBFaJNfNiIMPajCPANGABNeHFL0U='

  [mod.'github.com/yuin/goldmark']
    version = 'v1.8.5'
    hash = 'sha256-h3K8bFnBVwoAUzqRNP66GEhMUKGIA27f7PA7M1r6rp4='

  [mod.'github.com/zalando/go-keyring']
    version = 'v0.2.8'
    hash = 'sha256-TnsYicaHuDBFITZGWiAW9L7OxvpQ4XbBFpLpOI7NteI='

  [mod.'go4.org']
    version = 'v0.0.0-20260112195520-a5071408f32f'
    hash = 'sha256-K2sBsO4B4NwY2Hd5Do/LikhpvbL2prHh7cmOSvnTLrM='

  [mod.'golang.org/x/crypto']
    version = 'v0.54.0'
    hash = 'sha256-m8jsqlPuoPxGDjClzcAVbXf1aiU07L+9j7vYcqJu/0Q='

  [mod.'golang.org/x/sync']
    version = 'v0.22.0'
    hash = 'sha256-VZjl0fAM0p/nI81zh+pdBjzxFupx0UcKYXBBpL2ZS7k='

  [mod.'golang.org/x/sys']
    version = 'v0.47.0'
    hash = 'sha256-TpbRyWWqHjddP6QzUgAbaLd2EE0S+GYNRUIDJd18r98='

  [mod.'golang.org/x/text']
    version = 'v0.40.0'
    hash = 'sha256-LJfnki46XEreGbSgjl+DeqgcTsINTOu2owyXNvijMcA='

  [mod.'golang.org/x/time']
    version = 'v0.15.0'
    hash = 'sha256-5D24A65wn7k93Jj3+918UKjB9ccmGHPBEqjD2XDB92E='

  [mod.'libdb.so/ctxt']
    version = 'v0.0.0-20240229093153-2db38a5d3c12'
    hash = 'sha256-mViBj67wYeuD4mQKMP/4gQo9lFNO6J8HZztHw9ZGPlk='

  [mod.'libdb.so/go-emoji']
    version = 'v0.0.0-20240508073816-39776eee41ac'
    hash = 'sha256-Lsc8gcjZdlh/J95zoHACfE06xv8TojUIoVoCaugvLlY='

  [mod.'libdb.so/gotk4-sourceview/pkg']
    version = 'v0.0.0-20260808232043-f3d195566193'
    hash = 'sha256-CTyxtFELqaJtfUZJjqMbwKQ1J3Oc1vZYninO+ln8t1U='

  [mod.'libdb.so/gotk4-spelling/pkg']
    version = 'v0.0.0-20241128063647-a9edc40bddb0'
    hash = 'sha256-0q/N5Ui5kUM2JWpt2pgE310SniY5f4QU0ayD6YLag3w='
