#!/usr/bin/env bash
set -e

main() {
	need_env GITHUB_TOKEN
	need_env GITHUB_REPO
	need_env RELEASE_ID

	files=()
	for path in "$@"; do
		while read -r file; do
			files+=("$file")
		done < <(find "$path" -type f)
	done
	
	for file in "${files[@]}"; {
		echo "::info::Uploading $file"

		name=$(basename "$file")
		curl \
			-X POST \
			-o /dev/null \
			-S -s --fail-with-body \
			-H "Authorization: token $GITHUB_TOKEN" \
			-H "Accept: application/vnd.github.v3+json" \
			-H "Content-Type: application/x-executable" \
			--data-binary "@$file" \
			"https://uploads.github.com/repos/$GITHUB_REPO/releases/$RELEASE_ID/assets?name=$name"
	}
}

need_env() {
	local var="$1"
	[[ "${!var}" ]] || {
		echo "\$$var is not set" >&2
		exit 1
	}
}

main "$@"
